//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi1.Culture {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LANG {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LANG() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebApi1.Culture.LANG", typeof(LANG).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 安装时间 的本地化字符串。
        /// </summary>
        internal static string AnZhuangShiJian {
            get {
                return ResourceManager.GetString("AnZhuangShiJian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 版本 的本地化字符串。
        /// </summary>
        internal static string BanBeng {
            get {
                return ResourceManager.GetString("BanBeng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 版本管理 的本地化字符串。
        /// </summary>
        internal static string BanBengGuanLi {
            get {
                return ResourceManager.GetString("BanBengGuanLi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 版本号 的本地化字符串。
        /// </summary>
        internal static string BanBengHao {
            get {
                return ResourceManager.GetString("BanBengHao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 版本号已存在 的本地化字符串。
        /// </summary>
        internal static string BanBengHaoYiCunZai {
            get {
                return ResourceManager.GetString("BanBengHaoYiCunZai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 绑定 的本地化字符串。
        /// </summary>
        internal static string BangDing {
            get {
                return ResourceManager.GetString("BangDing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 帮助 的本地化字符串。
        /// </summary>
        internal static string BangZhu {
            get {
                return ResourceManager.GetString("BangZhu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存 的本地化字符串。
        /// </summary>
        internal static string BaoCun {
            get {
                return ResourceManager.GetString("BaoCun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 备注 的本地化字符串。
        /// </summary>
        internal static string BeiZhu {
            get {
                return ResourceManager.GetString("BeiZhu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编号 的本地化字符串。
        /// </summary>
        internal static string BianHao {
            get {
                return ResourceManager.GetString("BianHao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑 的本地化字符串。
        /// </summary>
        internal static string BianJi {
            get {
                return ResourceManager.GetString("BianJi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 标识 的本地化字符串。
        /// </summary>
        internal static string BiaoShi {
            get {
                return ResourceManager.GetString("BiaoShi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 标题 的本地化字符串。
        /// </summary>
        internal static string BiaoTi {
            get {
                return ResourceManager.GetString("BiaoTi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不能为空 的本地化字符串。
        /// </summary>
        internal static string BuNengWeiKong {
            get {
                return ResourceManager.GetString("BuNengWeiKong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作 的本地化字符串。
        /// </summary>
        internal static string CaoZuo {
            get {
                return ResourceManager.GetString("CaoZuo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {PropertyName}的长度为{MinLength}至{MaxLength}个字符 的本地化字符串。
        /// </summary>
        internal static string ChangDuQuJianFormat {
            get {
                return ResourceManager.GetString("ChangDuQuJianFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 长期有效 的本地化字符串。
        /// </summary>
        internal static string ChangQiYouXiao {
            get {
                return ResourceManager.GetString("ChangQiYouXiao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查询 的本地化字符串。
        /// </summary>
        internal static string ChaXun {
            get {
                return ResourceManager.GetString("ChaXun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 成功 的本地化字符串。
        /// </summary>
        internal static string ChengGong {
            get {
                return ResourceManager.GetString("ChengGong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 程序包 的本地化字符串。
        /// </summary>
        internal static string ChengXuBao {
            get {
                return ResourceManager.GetString("ChengXuBao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 程序配置 的本地化字符串。
        /// </summary>
        internal static string ChengXuPeiZhi {
            get {
                return ResourceManager.GetString("ChengXuPeiZhi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 程序已经运行，请勿重复操作 的本地化字符串。
        /// </summary>
        internal static string ChengXuYiJingYunXingQingWuChongFuCaoZuo {
            get {
                return ResourceManager.GetString("ChengXuYiJingYunXingQingWuChongFuCaoZuo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重置 的本地化字符串。
        /// </summary>
        internal static string ChongZhi {
            get {
                return ResourceManager.GetString("ChongZhi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重置为默认密码 的本地化字符串。
        /// </summary>
        internal static string ChongZhiWeiMoRenMiMa {
            get {
                return ResourceManager.GetString("ChongZhiWeiMoRenMiMa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建 的本地化字符串。
        /// </summary>
        internal static string ChuangJian {
            get {
                return ResourceManager.GetString("ChuangJian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 传真 的本地化字符串。
        /// </summary>
        internal static string ChuanZheng {
            get {
                return ResourceManager.GetString("ChuanZheng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 出生日期 的本地化字符串。
        /// </summary>
        internal static string ChuShengRiQi {
            get {
                return ResourceManager.GetString("ChuShengRiQi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 初始失败，请重新操作 的本地化字符串。
        /// </summary>
        internal static string ChuShiShiBaiQingChongXinCaoZuo {
            get {
                return ResourceManager.GetString("ChuShiShiBaiQingChongXinCaoZuo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 初始失败，请关闭程序重新启动 的本地化字符串。
        /// </summary>
        internal static string ChuShiShiBaiQingGuanBiChongXingQiDong {
            get {
                return ResourceManager.GetString("ChuShiShiBaiQingGuanBiChongXingQiDong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 次数 的本地化字符串。
        /// </summary>
        internal static string CiShu {
            get {
                return ResourceManager.GetString("CiShu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 错误 的本地化字符串。
        /// </summary>
        internal static string CuoWu {
            get {
                return ResourceManager.GetString("CuoWu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前版本 的本地化字符串。
        /// </summary>
        internal static string DangQianBanBeng {
            get {
                return ResourceManager.GetString("DangQianBanBeng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前为最新版本 的本地化字符串。
        /// </summary>
        internal static string DangQianWeiZuiXinBanBeng {
            get {
                return ResourceManager.GetString("DangQianWeiZuiXinBanBeng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 单价 的本地化字符串。
        /// </summary>
        internal static string DanJia {
            get {
                return ResourceManager.GetString("DanJia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 单位 的本地化字符串。
        /// </summary>
        internal static string DanWei {
            get {
                return ResourceManager.GetString("DanWei", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导出 的本地化字符串。
        /// </summary>
        internal static string DaoChu {
            get {
                return ResourceManager.GetString("DaoChu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 倒计时 的本地化字符串。
        /// </summary>
        internal static string DaoJiShi {
            get {
                return ResourceManager.GetString("DaoJiShi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导入 的本地化字符串。
        /// </summary>
        internal static string DaoRu {
            get {
                return ResourceManager.GetString("DaoRu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 登录 的本地化字符串。
        /// </summary>
        internal static string DengLu {
            get {
                return ResourceManager.GetString("DengLu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 登录账号 的本地化字符串。
        /// </summary>
        internal static string DengLuZhangHao {
            get {
                return ResourceManager.GetString("DengLuZhangHao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 电话 的本地化字符串。
        /// </summary>
        internal static string DianHua {
            get {
                return ResourceManager.GetString("DianHua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 订单 的本地化字符串。
        /// </summary>
        internal static string DingDan {
            get {
                return ResourceManager.GetString("DingDan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 地区数据 的本地化字符串。
        /// </summary>
        internal static string DiQuShuJu {
            get {
                return ResourceManager.GetString("DiQuShuJu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 地址 的本地化字符串。
        /// </summary>
        internal static string DiZhi {
            get {
                return ResourceManager.GetString("DiZhi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发布 的本地化字符串。
        /// </summary>
        internal static string FaBu {
            get {
                return ResourceManager.GetString("FaBu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发布时间 的本地化字符串。
        /// </summary>
        internal static string FaBuShiJian {
            get {
                return ResourceManager.GetString("FaBuShiJian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 返回登录 的本地化字符串。
        /// </summary>
        internal static string FanHuiDengLu {
            get {
                return ResourceManager.GetString("FanHuiDengLu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 反馈 的本地化字符串。
        /// </summary>
        internal static string FanKui {
            get {
                return ResourceManager.GetString("FanKui", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发送 的本地化字符串。
        /// </summary>
        internal static string FaSong {
            get {
                return ResourceManager.GetString("FaSong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发现新版本 的本地化字符串。
        /// </summary>
        internal static string FaXianXinBanBeng {
            get {
                return ResourceManager.GetString("FaXianXinBanBeng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更新 的本地化字符串。
        /// </summary>
        internal static string GengXin {
            get {
                return ResourceManager.GetString("GengXin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更新包 的本地化字符串。
        /// </summary>
        internal static string GengXinBao {
            get {
                return ResourceManager.GetString("GengXinBao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更新程序 的本地化字符串。
        /// </summary>
        internal static string GengXinChengXu {
            get {
                return ResourceManager.GetString("GengXinChengXu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更新类型 的本地化字符串。
        /// </summary>
        internal static string GengXinLeiXing {
            get {
                return ResourceManager.GetString("GengXinLeiXing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 个人 的本地化字符串。
        /// </summary>
        internal static string GeRen {
            get {
                return ResourceManager.GetString("GeRen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 个人用户 的本地化字符串。
        /// </summary>
        internal static string GeRenYongHu {
            get {
                return ResourceManager.GetString("GeRenYongHu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 功能权限 的本地化字符串。
        /// </summary>
        internal static string GongNengQuanXian {
            get {
                return ResourceManager.GetString("GongNengQuanXian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 共享 的本地化字符串。
        /// </summary>
        internal static string GongXiang {
            get {
                return ResourceManager.GetString("GongXiang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工作台 的本地化字符串。
        /// </summary>
        internal static string GongZuoTai {
            get {
                return ResourceManager.GetString("GongZuoTai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 购买 的本地化字符串。
        /// </summary>
        internal static string GouMai {
            get {
                return ResourceManager.GetString("GouMai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 管理 的本地化字符串。
        /// </summary>
        internal static string GuanLi {
            get {
                return ResourceManager.GetString("GuanLi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 管理工具 的本地化字符串。
        /// </summary>
        internal static string GuanLiGongJu {
            get {
                return ResourceManager.GetString("GuanLiGongJu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 管理员 的本地化字符串。
        /// </summary>
        internal static string GuanLiYuan {
            get {
                return ResourceManager.GetString("GuanLiYuan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 管理中心 的本地化字符串。
        /// </summary>
        internal static string GuanLiZhongXin {
            get {
                return ResourceManager.GetString("GuanLiZhongXin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关于 的本地化字符串。
        /// </summary>
        internal static string GuanYu {
            get {
                return ResourceManager.GetString("GuanYu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关于我们 的本地化字符串。
        /// </summary>
        internal static string GuanYuWoMen {
            get {
                return ResourceManager.GetString("GuanYuWoMen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过期 的本地化字符串。
        /// </summary>
        internal static string GuoQi {
            get {
                return ResourceManager.GetString("GuoQi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 行业数据 的本地化字符串。
        /// </summary>
        internal static string HangYeShuJu {
            get {
                return ResourceManager.GetString("HangYeShuJu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 会员码 的本地化字符串。
        /// </summary>
        internal static string HuiYuanMa {
            get {
                return ResourceManager.GetString("HuiYuanMa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IP地址库 的本地化字符串。
        /// </summary>
        internal static string IPDiZhiKu {
            get {
                return ResourceManager.GetString("IPDiZhiKu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 校验 的本地化字符串。
        /// </summary>
        internal static string JiaoYan {
            get {
                return ResourceManager.GetString("JiaoYan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 基础 的本地化字符串。
        /// </summary>
        internal static string JiChu {
            get {
                return ResourceManager.GetString("JiChu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 解绑 的本地化字符串。
        /// </summary>
        internal static string JieBang {
            get {
                return ResourceManager.GetString("JieBang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 结束 的本地化字符串。
        /// </summary>
        internal static string JieShu {
            get {
                return ResourceManager.GetString("JieShu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 结束时间 的本地化字符串。
        /// </summary>
        internal static string JieShuShiJian {
            get {
                return ResourceManager.GetString("JieShuShiJian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 解析 的本地化字符串。
        /// </summary>
        internal static string JieXi {
            get {
                return ResourceManager.GetString("JieXi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 禁止 的本地化字符串。
        /// </summary>
        internal static string JingZhi {
            get {
                return ResourceManager.GetString("JingZhi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开始 的本地化字符串。
        /// </summary>
        internal static string KaiShi {
            get {
                return ResourceManager.GetString("KaiShi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开始时间 的本地化字符串。
        /// </summary>
        internal static string KaiShiShiJian {
            get {
                return ResourceManager.GetString("KaiShiShiJian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 客户端 的本地化字符串。
        /// </summary>
        internal static string KeHuDuan {
            get {
                return ResourceManager.GetString("KeHuDuan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Key 的本地化字符串。
        /// </summary>
        internal static string Key {
            get {
                return ResourceManager.GetString("Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 空时默认 的本地化字符串。
        /// </summary>
        internal static string KongShiMoRen {
            get {
                return ResourceManager.GetString("KongShiMoRen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 来源 的本地化字符串。
        /// </summary>
        internal static string LaiYuan {
            get {
                return ResourceManager.GetString("LaiYuan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 类型 的本地化字符串。
        /// </summary>
        internal static string LeiXing {
            get {
                return ResourceManager.GetString("LeiXing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 联系地址 的本地化字符串。
        /// </summary>
        internal static string LianXiDiZhi {
            get {
                return ResourceManager.GetString("LianXiDiZhi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 浏览器 的本地化字符串。
        /// </summary>
        internal static string LiuLanQi {
            get {
                return ResourceManager.GetString("LiuLanQi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 留言 的本地化字符串。
        /// </summary>
        internal static string LiuYan {
            get {
                return ResourceManager.GetString("LiuYan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 路径错误 的本地化字符串。
        /// </summary>
        internal static string LuJingCuoWu {
            get {
                return ResourceManager.GetString("LuJingCuoWu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 描述 的本地化字符串。
        /// </summary>
        internal static string MiaoShu {
            get {
                return ResourceManager.GetString("MiaoShu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密码 的本地化字符串。
        /// </summary>
        internal static string MiMa {
            get {
                return ResourceManager.GetString("MiMa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重置密码 的本地化字符串。
        /// </summary>
        internal static string MiMaChongZhi {
            get {
                return ResourceManager.GetString("MiMaChongZhi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 旧密码 的本地化字符串。
        /// </summary>
        internal static string MiMaJiu {
            get {
                return ResourceManager.GetString("MiMaJiu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 记住密码 的本地化字符串。
        /// </summary>
        internal static string MiMaJiZhu {
            get {
                return ResourceManager.GetString("MiMaJiZhu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认密码 的本地化字符串。
        /// </summary>
        internal static string MiMaQueReng {
            get {
                return ResourceManager.GetString("MiMaQueReng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新密码 的本地化字符串。
        /// </summary>
        internal static string MiMaXin {
            get {
                return ResourceManager.GetString("MiMaXin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新密码与确认密码不同 的本地化字符串。
        /// </summary>
        internal static string MiMaXinYuQueRenBuTong {
            get {
                return ResourceManager.GetString("MiMaXinYuQueRenBuTong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改密码 的本地化字符串。
        /// </summary>
        internal static string MiMaXiuGai {
            get {
                return ResourceManager.GetString("MiMaXiuGai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 原密码 的本地化字符串。
        /// </summary>
        internal static string MiMaYuan {
            get {
                return ResourceManager.GetString("MiMaYuan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 找回密码？ 的本地化字符串。
        /// </summary>
        internal static string MiMaZhaoHui {
            get {
                return ResourceManager.GetString("MiMaZhaoHui", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 名称 的本地化字符串。
        /// </summary>
        internal static string MingCheng {
            get {
                return ResourceManager.GetString("MingCheng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密钥 的本地化字符串。
        /// </summary>
        internal static string MiYao {
            get {
                return ResourceManager.GetString("MiYao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 模版下载 的本地化字符串。
        /// </summary>
        internal static string MoBanXiaZai {
            get {
                return ResourceManager.GetString("MoBanXiaZai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 默认 的本地化字符串。
        /// </summary>
        internal static string MoRen {
            get {
                return ResourceManager.GetString("MoRen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 默认选择 的本地化字符串。
        /// </summary>
        internal static string MoRenXuanZe {
            get {
                return ResourceManager.GetString("MoRenXuanZe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 默认状态 的本地化字符串。
        /// </summary>
        internal static string MoRenZhuangTai {
            get {
                return ResourceManager.GetString("MoRenZhuangTai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 内容 的本地化字符串。
        /// </summary>
        internal static string NeiRong {
            get {
                return ResourceManager.GetString("NeiRong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 内容 的本地化字符串。
        /// </summary>
        internal static string NeiRong1 {
            get {
                return ResourceManager.GetString("NeiRong1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 内容为空 的本地化字符串。
        /// </summary>
        internal static string NeiRongWeiKong {
            get {
                return ResourceManager.GetString("NeiRongWeiKong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 昵称 的本地化字符串。
        /// </summary>
        internal static string NiCheng {
            get {
                return ResourceManager.GetString("NiCheng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 配置 的本地化字符串。
        /// </summary>
        internal static string PeiZhi {
            get {
                return ResourceManager.GetString("PeiZhi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 配置文件 的本地化字符串。
        /// </summary>
        internal static string PeiZhiWenJian {
            get {
                return ResourceManager.GetString("PeiZhiWenJian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启动 的本地化字符串。
        /// </summary>
        internal static string QiDong {
            get {
                return ResourceManager.GetString("QiDong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 切换 的本地化字符串。
        /// </summary>
        internal static string QieHuan {
            get {
                return ResourceManager.GetString("QieHuan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 切换 的本地化字符串。
        /// </summary>
        internal static string QieHuan1 {
            get {
                return ResourceManager.GetString("QieHuan1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请联系客服获取帮助或信息！ 的本地化字符串。
        /// </summary>
        internal static string QingLianXiKeFuHuoQuBangZhuHuoXinXi {
            get {
                return ResourceManager.GetString("QingLianXiKeFuHuoQuBangZhuHuoXinXi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入 的本地化字符串。
        /// </summary>
        internal static string QingShuRu {
            get {
                return ResourceManager.GetString("QingShuRu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入{PropertyName} 的本地化字符串。
        /// </summary>
        internal static string QingShuRuFormat {
            get {
                return ResourceManager.GetString("QingShuRuFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入关键字搜索 的本地化字符串。
        /// </summary>
        internal static string QingShuRuGuanJianZi {
            get {
                return ResourceManager.GetString("QingShuRuGuanJianZi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入有效的 的本地化字符串。
        /// </summary>
        internal static string QingShuRuYouXiaoDe {
            get {
                return ResourceManager.GetString("QingShuRuYouXiaoDe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入有效的{PropertyName} 的本地化字符串。
        /// </summary>
        internal static string QingShuRuYouXiaoFormat {
            get {
                return ResourceManager.GetString("QingShuRuYouXiaoFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  从{0}至{1} 的本地化字符串。
        /// </summary>
        internal static string QiZhiFormat {
            get {
                return ResourceManager.GetString("QiZhiFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 起止信息 的本地化字符串。
        /// </summary>
        internal static string QiZhiXinXi {
            get {
                return ResourceManager.GetString("QiZhiXinXi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 全部 的本地化字符串。
        /// </summary>
        internal static string QuanBu {
            get {
                return ResourceManager.GetString("QuanBu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定 的本地化字符串。
        /// </summary>
        internal static string QueDing {
            get {
                return ResourceManager.GetString("QueDing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认 的本地化字符串。
        /// </summary>
        internal static string QueRen {
            get {
                return ResourceManager.GetString("QueRen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消 的本地化字符串。
        /// </summary>
        internal static string QuXiao {
            get {
                return ResourceManager.GetString("QuXiao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 手机认证 的本地化字符串。
        /// </summary>
        internal static string RengZhengShouJi {
            get {
                return ResourceManager.GetString("RengZhengShouJi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 邮箱认证 的本地化字符串。
        /// </summary>
        internal static string RengZhengYouXiang {
            get {
                return ResourceManager.GetString("RengZhengYouXiang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 证件认证 的本地化字符串。
        /// </summary>
        internal static string RengZhengZhengJian {
            get {
                return ResourceManager.GetString("RengZhengZhengJian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 任务创建 的本地化字符串。
        /// </summary>
        internal static string RenWuChuangJian {
            get {
                return ResourceManager.GetString("RenWuChuangJian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 认证 的本地化字符串。
        /// </summary>
        internal static string RenZheng {
            get {
                return ResourceManager.GetString("RenZheng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 日期 的本地化字符串。
        /// </summary>
        internal static string RiQi {
            get {
                return ResourceManager.GetString("RiQi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 日志记录 的本地化字符串。
        /// </summary>
        internal static string RiZhiJiLu {
            get {
                return ResourceManager.GetString("RiZhiJiLu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 日志记录器 的本地化字符串。
        /// </summary>
        internal static string RiZhiJiLuQi {
            get {
                return ResourceManager.GetString("RiZhiJiLuQi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除 的本地化字符串。
        /// </summary>
        internal static string ShanChu {
            get {
                return ResourceManager.GetString("ShanChu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上传 的本地化字符串。
        /// </summary>
        internal static string ShangChuan {
            get {
                return ResourceManager.GetString("ShangChuan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 生成 的本地化字符串。
        /// </summary>
        internal static string ShengCheng {
            get {
                return ResourceManager.GetString("ShengCheng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置 的本地化字符串。
        /// </summary>
        internal static string SheZhi {
            get {
                return ResourceManager.GetString("SheZhi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 失败 的本地化字符串。
        /// </summary>
        internal static string ShiBai {
            get {
                return ResourceManager.GetString("ShiBai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 识别结果 的本地化字符串。
        /// </summary>
        internal static string ShiBieJieGuo {
            get {
                return ResourceManager.GetString("ShiBieJieGuo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 识别结果为空 的本地化字符串。
        /// </summary>
        internal static string ShiBieJieGuoWeiKong {
            get {
                return ResourceManager.GetString("ShiBieJieGuoWeiKong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 时间 的本地化字符串。
        /// </summary>
        internal static string ShiJian {
            get {
                return ResourceManager.GetString("ShiJian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 试用版 的本地化字符串。
        /// </summary>
        internal static string ShiYongBan {
            get {
                return ResourceManager.GetString("ShiYongBan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 使用次数 的本地化字符串。
        /// </summary>
        internal static string ShiYongCiShu {
            get {
                return ResourceManager.GetString("ShiYongCiShu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 手机 的本地化字符串。
        /// </summary>
        internal static string ShouJi {
            get {
                return ResourceManager.GetString("ShouJi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 手机号 的本地化字符串。
        /// </summary>
        internal static string ShouJiHao {
            get {
                return ResourceManager.GetString("ShouJiHao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 手机号码 的本地化字符串。
        /// </summary>
        internal static string ShouJiHaoMa {
            get {
                return ResourceManager.GetString("ShouJiHaoMa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 授权使用次数已超出 的本地化字符串。
        /// </summary>
        internal static string ShouQuanShiYongCiShuYiChaoChu {
            get {
                return ResourceManager.GetString("ShouQuanShiYongCiShuYiChaoChu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 授权文件错误 的本地化字符串。
        /// </summary>
        internal static string ShouQuanWenJianCuoWu {
            get {
                return ResourceManager.GetString("ShouQuanWenJianCuoWu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 授权信息错误 的本地化字符串。
        /// </summary>
        internal static string ShouQuanXinXiCuoWu {
            get {
                return ResourceManager.GetString("ShouQuanXinXiCuoWu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 授权信息已过期 的本地化字符串。
        /// </summary>
        internal static string ShouQuanYiGuoQi {
            get {
                return ResourceManager.GetString("ShouQuanYiGuoQi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 首页 的本地化字符串。
        /// </summary>
        internal static string ShouYe {
            get {
                return ResourceManager.GetString("ShouYe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数量 的本地化字符串。
        /// </summary>
        internal static string ShuLiang {
            get {
                return ResourceManager.GetString("ShuLiang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 搜索 的本地化字符串。
        /// </summary>
        internal static string SouSuo {
            get {
                return ResourceManager.GetString("SouSuo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加 的本地化字符串。
        /// </summary>
        internal static string TianJia {
            get {
                return ResourceManager.GetString("TianJia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 天数 的本地化字符串。
        /// </summary>
        internal static string TianShu {
            get {
                return ResourceManager.GetString("TianShu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提交 的本地化字符串。
        /// </summary>
        internal static string TiJiao {
            get {
                return ResourceManager.GetString("TiJiao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 通知类型 的本地化字符串。
        /// </summary>
        internal static string TongZhiLeiXin {
            get {
                return ResourceManager.GetString("TongZhiLeiXin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 退出 的本地化字符串。
        /// </summary>
        internal static string TuiChu {
            get {
                return ResourceManager.GetString("TuiChu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未绑定 的本地化字符串。
        /// </summary>
        internal static string WeiBangDing {
            get {
                return ResourceManager.GetString("WeiBangDing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未找到{0} 的本地化字符串。
        /// </summary>
        internal static string WeiZhaoDaoFormat {
            get {
                return ResourceManager.GetString("WeiZhaoDaoFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文档 的本地化字符串。
        /// </summary>
        internal static string WenDang {
            get {
                return ResourceManager.GetString("WenDang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件 的本地化字符串。
        /// </summary>
        internal static string WenJian {
            get {
                return ResourceManager.GetString("WenJian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件上传 的本地化字符串。
        /// </summary>
        internal static string WenJianShangChuan {
            get {
                return ResourceManager.GetString("WenJianShangChuan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 我已阅读 的本地化字符串。
        /// </summary>
        internal static string WoYiYueDu {
            get {
                return ResourceManager.GetString("WoYiYueDu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 我已阅读《注册协议》 的本地化字符串。
        /// </summary>
        internal static string WoYiYueDuZhuCeXieYi {
            get {
                return ResourceManager.GetString("WoYiYueDuZhuCeXieYi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 性别 的本地化字符串。
        /// </summary>
        internal static string XingBie {
            get {
                return ResourceManager.GetString("XingBie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 姓名 的本地化字符串。
        /// </summary>
        internal static string XingMing {
            get {
                return ResourceManager.GetString("XingMing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 信息 的本地化字符串。
        /// </summary>
        internal static string XinXi {
            get {
                return ResourceManager.GetString("XinXi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 系统 的本地化字符串。
        /// </summary>
        internal static string XiTong {
            get {
                return ResourceManager.GetString("XiTong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 系统数据不允许操作 的本地化字符串。
        /// </summary>
        internal static string XiTongShuJuBuYunXuCaoZuo {
            get {
                return ResourceManager.GetString("XiTongShuJuBuYunXuCaoZuo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改 的本地化字符串。
        /// </summary>
        internal static string XiuGai {
            get {
                return ResourceManager.GetString("XiuGai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择 的本地化字符串。
        /// </summary>
        internal static string XuanZe {
            get {
                return ResourceManager.GetString("XuanZe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 验证码 的本地化字符串。
        /// </summary>
        internal static string YanZhengMa {
            get {
                return ResourceManager.GetString("YanZhengMa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取验证码 的本地化字符串。
        /// </summary>
        internal static string YanZhengMaHuoQu {
            get {
                return ResourceManager.GetString("YanZhengMaHuoQu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 业务 的本地化字符串。
        /// </summary>
        internal static string YeWu {
            get {
                return ResourceManager.GetString("YeWu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已绑定 的本地化字符串。
        /// </summary>
        internal static string YiBangDing {
            get {
                return ResourceManager.GetString("YiBangDing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}已存在 的本地化字符串。
        /// </summary>
        internal static string YiCunZaiFormat {
            get {
                return ResourceManager.GetString("YiCunZaiFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已过期 的本地化字符串。
        /// </summary>
        internal static string YiGuoQi {
            get {
                return ResourceManager.GetString("YiGuoQi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已解绑 的本地化字符串。
        /// </summary>
        internal static string YiJieBang {
            get {
                return ResourceManager.GetString("YiJieBang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 应用 的本地化字符串。
        /// </summary>
        internal static string YingYong {
            get {
                return ResourceManager.GetString("YingYong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 应用版本 的本地化字符串。
        /// </summary>
        internal static string YingYongBanBeng {
            get {
                return ResourceManager.GetString("YingYongBanBeng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 应用程序 的本地化字符串。
        /// </summary>
        internal static string YingYongChengXu {
            get {
                return ResourceManager.GetString("YingYongChengXu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 应用配置 的本地化字符串。
        /// </summary>
        internal static string YingYongPeiZhi {
            get {
                return ResourceManager.GetString("YingYongPeiZhi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 应用项目 的本地化字符串。
        /// </summary>
        internal static string YingYongXiangMu {
            get {
                return ResourceManager.GetString("YingYongXiangMu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已使用 的本地化字符串。
        /// </summary>
        internal static string YiShiYong {
            get {
                return ResourceManager.GetString("YiShiYong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已选中&lt;em&gt;{0}&lt;/em&gt;项 的本地化字符串。
        /// </summary>
        internal static string YiXuanZeXiang {
            get {
                return ResourceManager.GetString("YiXuanZeXiang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 译者 的本地化字符串。
        /// </summary>
        internal static string YiZhe {
            get {
                return ResourceManager.GetString("YiZhe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户 的本地化字符串。
        /// </summary>
        internal static string YongHu {
            get {
                return ResourceManager.GetString("YongHu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户导入 的本地化字符串。
        /// </summary>
        internal static string YongHuDaoRu {
            get {
                return ResourceManager.GetString("YongHuDaoRu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户登录 的本地化字符串。
        /// </summary>
        internal static string YongHuDengLu {
            get {
                return ResourceManager.GetString("YongHuDengLu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户类型 的本地化字符串。
        /// </summary>
        internal static string YongHuLeiXing {
            get {
                return ResourceManager.GetString("YongHuLeiXing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户类型 [{0}] 不允许登录 的本地化字符串。
        /// </summary>
        internal static string YongHuLeiXingBuYunXuDengLuFormat {
            get {
                return ResourceManager.GetString("YongHuLeiXingBuYunXuDengLuFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户类型 [{0}] 不允许注册 的本地化字符串。
        /// </summary>
        internal static string YongHuLeiXingBuYunXuZhuCeFormat {
            get {
                return ResourceManager.GetString("YongHuLeiXingBuYunXuZhuCeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户名 的本地化字符串。
        /// </summary>
        internal static string YongHuMing {
            get {
                return ResourceManager.GetString("YongHuMing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户名/手机号码/邮箱地址 的本地化字符串。
        /// </summary>
        internal static string YongHuMingShouJihaoMaYouXiangDiZhi {
            get {
                return ResourceManager.GetString("YongHuMingShouJihaoMaYouXiangDiZhi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户配置 的本地化字符串。
        /// </summary>
        internal static string YongHuPeiZhi {
            get {
                return ResourceManager.GetString("YongHuPeiZhi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未找到用户 的本地化字符串。
        /// </summary>
        internal static string YongHuWeiZhaoDao {
            get {
                return ResourceManager.GetString("YongHuWeiZhaoDao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户异常 的本地化字符串。
        /// </summary>
        internal static string YongHuYiChang {
            get {
                return ResourceManager.GetString("YongHuYiChang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户已存在 的本地化字符串。
        /// </summary>
        internal static string YongHuYiCunZai {
            get {
                return ResourceManager.GetString("YongHuYiCunZai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户状态 {0} 请联系客服 的本地化字符串。
        /// </summary>
        internal static string YongHuZhuangTaiWeiFormat {
            get {
                return ResourceManager.GetString("YongHuZhuangTaiWeiFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户注册 的本地化字符串。
        /// </summary>
        internal static string YongHuZhuCe {
            get {
                return ResourceManager.GetString("YongHuZhuCe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新用户注册 的本地化字符串。
        /// </summary>
        internal static string YongYuZhuCeXin {
            get {
                return ResourceManager.GetString("YongYuZhuCeXin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 优惠 的本地化字符串。
        /// </summary>
        internal static string YouHui {
            get {
                return ResourceManager.GetString("YouHui", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 邮箱 的本地化字符串。
        /// </summary>
        internal static string YouXiang {
            get {
                return ResourceManager.GetString("YouXiang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 邮箱地址 的本地化字符串。
        /// </summary>
        internal static string YouXiangDiZhi {
            get {
                return ResourceManager.GetString("YouXiangDiZhi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 有效时间 的本地化字符串。
        /// </summary>
        internal static string YouXiaoShiJian {
            get {
                return ResourceManager.GetString("YouXiaoShiJian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 有效天数 的本地化字符串。
        /// </summary>
        internal static string YouXiaoTianShu {
            get {
                return ResourceManager.GetString("YouXiaoTianShu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 有效天数 的本地化字符串。
        /// </summary>
        internal static string YouXiaoTianShu1 {
            get {
                return ResourceManager.GetString("YouXiaoTianShu1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 允许 的本地化字符串。
        /// </summary>
        internal static string YunXu {
            get {
                return ResourceManager.GetString("YunXu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 语言 的本地化字符串。
        /// </summary>
        internal static string YuYan {
            get {
                return ResourceManager.GetString("YuYan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 账号 的本地化字符串。
        /// </summary>
        internal static string ZhangHao {
            get {
                return ResourceManager.GetString("ZhangHao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 没有账号 的本地化字符串。
        /// </summary>
        internal static string ZhangHaoMeiYou {
            get {
                return ResourceManager.GetString("ZhangHaoMeiYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 帐号已存在 的本地化字符串。
        /// </summary>
        internal static string ZhangHaoYiCunZai {
            get {
                return ResourceManager.GetString("ZhangHaoYiCunZai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已有账号 的本地化字符串。
        /// </summary>
        internal static string ZhangHaoYiYou {
            get {
                return ResourceManager.GetString("ZhangHaoYiYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正式版 的本地化字符串。
        /// </summary>
        internal static string ZhengShiBan {
            get {
                return ResourceManager.GetString("ZhengShiBan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在启动 的本地化字符串。
        /// </summary>
        internal static string ZhengZaiQiDong {
            get {
                return ResourceManager.GetString("ZhengZaiQiDong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 值 的本地化字符串。
        /// </summary>
        internal static string Zhi {
            get {
                return ResourceManager.GetString("Zhi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 支付 的本地化字符串。
        /// </summary>
        internal static string ZhiFu {
            get {
                return ResourceManager.GetString("ZhiFu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 中心 的本地化字符串。
        /// </summary>
        internal static string ZhongXin {
            get {
                return ResourceManager.GetString("ZhongXin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 状态 的本地化字符串。
        /// </summary>
        internal static string ZhuangTai {
            get {
                return ResourceManager.GetString("ZhuangTai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}状态为{1}，不允许操作 的本地化字符串。
        /// </summary>
        internal static string ZhuangTaiWeiBuYunXuCaoZuoFormat {
            get {
                return ResourceManager.GetString("ZhuangTaiWeiBuYunXuCaoZuoFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 注册 的本地化字符串。
        /// </summary>
        internal static string ZhuCe {
            get {
                return ResourceManager.GetString("ZhuCe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 《注册协议》 的本地化字符串。
        /// </summary>
        internal static string ZhuCeXieYi {
            get {
                return ResourceManager.GetString("ZhuCeXieYi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 主界面 的本地化字符串。
        /// </summary>
        internal static string ZhuJieMian {
            get {
                return ResourceManager.GetString("ZhuJieMian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 准备更新，正在关闭进程 的本地化字符串。
        /// </summary>
        internal static string ZhunBeiGengXinZhengZaiGuanBiJingCheng {
            get {
                return ResourceManager.GetString("ZhunBeiGengXinZhengZaiGuanBiJingCheng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 资料 的本地化字符串。
        /// </summary>
        internal static string ZiLiao {
            get {
                return ResourceManager.GetString("ZiLiao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 资源 的本地化字符串。
        /// </summary>
        internal static string ZiYuan {
            get {
                return ResourceManager.GetString("ZiYuan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最新版本 的本地化字符串。
        /// </summary>
        internal static string ZuiXinBanBeng {
            get {
                return ResourceManager.GetString("ZuiXinBanBeng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 作业 的本地化字符串。
        /// </summary>
        internal static string ZuoYe {
            get {
                return ResourceManager.GetString("ZuoYe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 作者 的本地化字符串。
        /// </summary>
        internal static string ZuoZhe {
            get {
                return ResourceManager.GetString("ZuoZhe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 组织 的本地化字符串。
        /// </summary>
        internal static string ZuZhi {
            get {
                return ResourceManager.GetString("ZuZhi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 组织成员 的本地化字符串。
        /// </summary>
        internal static string ZuZhiChengYuan {
            get {
                return ResourceManager.GetString("ZuZhiChengYuan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请从组织用户页面对应相关组织操作 的本地化字符串。
        /// </summary>
        internal static string ZuZhiChengYuanGuanLiCaoZuoTiShi {
            get {
                return ResourceManager.GetString("ZuZhiChengYuanGuanLiCaoZuoTiShi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 继承组织用户 的本地化字符串。
        /// </summary>
        internal static string ZuZhiChengYuanJiCheng {
            get {
                return ResourceManager.GetString("ZuZhiChengYuanJiCheng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 成员数量 的本地化字符串。
        /// </summary>
        internal static string ZuZhiChengYuanShuLiang {
            get {
                return ResourceManager.GetString("ZuZhiChengYuanShuLiang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 组织成员数量超过 [{0}] 个 的本地化字符串。
        /// </summary>
        internal static string ZuZhiChengYunShuLiangChaoGuoFormat {
            get {
                return ResourceManager.GetString("ZuZhiChengYunShuLiangChaoGuoFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 成员 的本地化字符串。
        /// </summary>
        internal static string ZuZhiDeChengYuan {
            get {
                return ResourceManager.GetString("ZuZhiDeChengYuan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 组织用户 的本地化字符串。
        /// </summary>
        internal static string ZuZhiYongHu {
            get {
                return ResourceManager.GetString("ZuZhiYongHu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 组织子账号数量 的本地化字符串。
        /// </summary>
        internal static string ZuZhiZiZhangHaoShuLiang {
            get {
                return ResourceManager.GetString("ZuZhiZiZhangHaoShuLiang", resourceCulture);
            }
        }
    }
}
